# site settings

title: cvless
description: Jekyll theme for a beautiful online CV
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
url: noobcoder-10.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/noobcoder-10/noobcoder-10.github.io

# author settings

author:
  name: Place Holder
  email: noobcoder-10@gmail.com
photo: /assets/jpg/thanmaisai_logo.png

# social media links

social:
  facebook: username
  github: username
  instagram: username
  linkedin: username
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
